### ISSUE TITLE
slicer does not accept knives

### ISSUE THREAD

**Issue by Emmulah** [PssbleTrngle/SliceAndDice#129]
### What happened?

cannot equip any type of knife to the slicer. knives in jei do not show "allowed tools" tag, although when i check in the mod jar i see that farmersdelight:tools/knives is an allowed tool. 

### Loader

forge

### Mod Version

2.3.2

### Minecraft Version

1.19

### Relevant log output

```Shell
https://gist.github.com/Emmulah/50a7d2c344073341df00a2d5eb44a4d1
```

**Comment by PssbleTrngle** [comment]
If you look at the log output around line 2375, it says two axe items that are added to the `#forge:tools/axes` tag are missing, probably an incorrect tag definition. Since the `#allowed_tools` tag includes the axe tag, it also fails to load due to that.
You can find the incorrect axe tag definition (probably druidcraft itself) and open an issue there

**Comment by Emmulah** [comment]
we don't even have druidcraft haha, i did look through the kubejs tags and it seems you were correct though. i've removed those tags and it resolved the issue! thank you so much for the quick response, this had me stumped.
