### ISSUE TITLE
[Compat] Compatibility with Farmer's Delight Refabricated [Fabric 1.20.1]

### ISSUE THREAD

**Issue by pokesmells** [PssbleTrngle/SliceAndDice#140]
### Describe the feature you have in mind.

The new port of Farmer's Delight is not supported yet, and doesn't work with Slice & Dice.
https://www.curseforge.com/minecraft/mc-mods/farmers-delight-refabricated

### Does this solve a particular problem?

It offers more support for a better port which is more faithful to the original mod on Forge, and so Slice & Dice can be used alongside with the new port without crashing when generating a new world.

**Comment by squimbo** [comment]
Would kill for this 👍

**Comment by Allexio** [comment]
> ### Describe the feature you have in mind.
> The new port of Farmer's Delight is not supported yet, and doesn't work with Slice & Dice. https://www.curseforge.com/minecraft/mc-mods/farmers-delight-refabricated
> 
> ### Does this solve a particular problem?
> It offers more support for a better port which is more faithful to the original mod on Forge, and so Slice & Dice can be used alongside with the new port without crashing when generating a new world.

A "better port" is very subjective, especially when you consider how it was made:

- Not contacting the original FD fabric author
- Not contacting other FD fabric add-on authors
- Not properly disclosing the change to users/modpack creators
- Re-using the same mod ID
- ...while also updating the version number to be "2.0" to make it seem like they updated the original mod when in fact you did something completely different
- Making their other mods (supplementaries) incompatible with the original with no explanation
  - which resulted in multiple github issues about this as the error shown made no sense and referred to a mod that should not exist (fd fabric 2.0 when in fact it should have been FD refabricated 1.0)
  - without forgetting to include a shameless plug to their own new version
  - and not mentioning that other FD fabric add-ons would effectively break (or being purposefully vague on the subject) just to try and get people to update
- Criticising the original work
- When asked if the port was necessary, instead of providing this detailed description, MehVahdJukaar just replied with "is anything necessary" further escalating drama for no reason.
- In fact, even the github "changes" page still does not address the issue that is compatibility with all the FD fabric add-ons that people use...

As much as I am a firm believer in open source and the healthy community that is the modding scene, this goes against so much that I believe in that I can not in good conscience use this mod or any other mod from MehVahdJukaar.

**Comment by Allexio** [comment]
And for the record, let's face it, the only reason you want it updated is because you want to use the latest supplementaries that forces you to use MehVahdJukaar's version. **Not** because the original port was inadequate.

**Comment by pokesmells** [comment]
> And for the record, let's face it, the only reason you want it updated is because you want to use the latest Supplementaries that forces you to use MehVahdJukaar's version. **Not** because the original port was inadequate.


No, it's not merely for that reason only, if you would've actually taken a look at Farmer's Delight Refabricated, it has significantly less trash in it's code, and it has removed many many bits of ambiguous code.


I want it because it's cleaner internally and more close to the actual original mod on Forge. 


Second, you need not contact the original devs due to the absolute uncertainty and lack of responses to PR's.


I merely want support for a port that is faithful to the original codebase, and is cleaner internally.

**Comment by bravely-beep** [comment]
> And for the record, let's face it, the only reason you want it updated is because you want to use the latest supplementaries that forces you to use MehVahdJukaar's version. **Not** because the original port was inadequate.

This is a pretty disrespectful response that makes a bunch of assumptions about other people. If you're against supporting the new FD port for moral reasons, sure, but don't bring personal attacks into it.

Personally I use the new FD port as it's more up-to-date with the Forge upstream version, and I'd be quite pleased if this mod has support for it added.

**Comment by pokesmells** [comment]
> > And for the record, let's face it, the only reason you want it updated is because you want to use the latest supplementaries that forces you to use MehVahdJukaar's version. **Not** because the original port was inadequate.
> 
> This is a pretty disrespectful response that makes a bunch of assumptions about other people. If you're against supporting the new FD port for moral reasons, sure, but don't bring personal attacks into it.
> 
> Personally I use the new FD port as it's more up-to-date with the Forge upstream version, and I'd be quite pleased if this mod has support for it added.

Agreed, but we had talked it out on discord, but again, I did mention to them that it was distasteful for that last comment.

All in all, let me support and use what I want.

**Comment by TheLegendofSaram** [comment]
this is reddit now

**Comment by PssbleTrngle** [comment]
This will very likely happen, although as soon as it does, the other implementation will no longer be supported

**Comment by pokesmells** [comment]
> This will very likely happen, although as soon as it does, the other implementation will no longer be supported

The other version was recently listed as "Deprecated"
![image](https://github.com/PssbleTrngle/SliceAndDice/assets/33227568/bcb180d3-56fd-4d0d-9599-43c4a8a7de9c)

So many others may soon drop support for it as well.

**Comment by Allexio** [comment]
More than the mod now being deprecated, the mod author behind the original port basically quit modding because of what happened, which is understandable.

**Comment by dhouck** [comment]
> More than the mod now being deprecated, the mod author behind the original port basically quit modding because of what happened, which is understandable.

Can you provide a link to this?  I canʼt find any acknowledgement at all besides changing the CF page to say deprecated, and it looks like they hadnʼt been doing any development for months.

**Comment by Allexio** [comment]
There is no link, it all happened on his discord, which he now shut down.
Multiple people were present when it went down.

**Comment by ninjaeon** [comment]
> And for the record, let's face it, the only reason you want it updated is because you want to use the latest supplementaries that forces you to use MehVahdJukaar's version. **Not** because the original port was inadequate.

I'm in this boat.  So for now, it's stay with the original port farmers-delight-fabric-1.4.3.jar and supplementaries-1.20-2.8.7-fabric.jar so I can keep using Slice & Dice.  Thank you for this great mod!

**Comment by PssbleTrngle** [comment]
finally done, let me know if everything still works
