### ISSUE TITLE
Fabric version?

### ISSUE THREAD

**Issue by ryleu** [PssbleTrngle/SliceAndDice#28]
### Describe the feature you have in mind.

I'd love to see a fabric version of this mod, as there are now fabric versions of both create and farmer's delight. If you're not interested, feel free to just close the issue.

### Does this solve a particular problem?

Nope. Just figured I'd ask because no one else has.

**Comment by ClaudiusMinimus** [comment]
I was using your Slice & Dice for my pack, [Create Conquest Arcane](https://www.curseforge.com/minecraft/modpacks/create-conquest-arcane) for 1.18.2, then one of the main mods in my pack, Conquest Reforge took a new direction. It looks like they are dropping Forge going forward and is now supporting Fabric for 1.19.2. Many of the mods I use are available in both forge and fabric or there is an equivalent in Fabric with a few exceptions, such as Slice & Dice. I see this issue was opened in Jan and not closed, which provides some hope. Is a fabric version being considered? If so, wonderful! If not, would you allow me to use assets from it? I am not a Java dev, so I cannot port to Fabric but might be able to use the assets to make a datapack doing roughly the same thing. I am most interested in the sprinkler head and slice & dice machine.

 

Thank you,

CM

**Comment by PssbleTrngle** [comment]
I have been trying to set up some sort multiloader repository for both forge & fabric to keep code duplication to a minimum, but I was unable to do it as for now. I am definitely interested in creating a fabric port, but I would like to find a more elegant solution than having two repositories that contain 95% of the same code

**Comment by ClaudiusMinimus** [comment]
Thanks for the update! I'll see if I can find something. I have a similar situation with Creatania, a forge mod that works with Create and Botania. My developer friend does not want to port Creatania to Fabric and I need it. Hopefully, we can find a way for Forge and Fabric to play nicely on GitHub. You might check with Latvian.dev (dev for kubejs - they seem to share Fabric and Forge code bases)

**Comment by PssbleTrngle** [comment]
Hi guys, good news, I have decided to port it to fabric and have uploaded a first alpha.
Everything should work as expected but you can never be sure

**Comment by ClaudiusMinimus** [comment]
Wow! That is Fantastic! It feels like Christmas!

**Comment by ClaudiusMinimus** [comment]
Can you provide a link that is accessible? :smile: 
![image](https://user-images.githubusercontent.com/17887664/235154581-ca492787-1264-4ddc-bac4-1f3a62f6162e.png)
![image](https://user-images.githubusercontent.com/17887664/235154930-0259af76-8dfa-48fc-8fc9-2b6b4c7df44c.png)

**Comment by PssbleTrngle** [comment]
CurseForge does not want me to upload it for some reason, it disappears shortly after I upload it every time. For now you can download it on Modrinth. 
And I changed the repo visibility to public, forgot about that

**Comment by ClaudiusMinimus** [comment]
Thanks! 
I have been meaning to port my packs to Modrinth. Is it better than CF?

**Comment by ClaudiusMinimus** [comment]
Crashed as soon I launched the pack
https://mclo.gs/XBFQEBe
Update: Probably should have started a new issue

**Comment by PssbleTrngle** [comment]
There is a new beta release that should have this fixed

**Comment by ClaudiusMinimus** [comment]
It did! Thanks! Will be in my next release.
Thought you might want to see this
![image](https://user-images.githubusercontent.com/17887664/236528624-6ff8e8db-c242-4e6f-a5ed-40fbf22fed29.png)

**Comment by PssbleTrngle** [comment]
Oh true, I forgot that the bucket model was using the forge built-in system, I'll have to replace that on the fabric port.
I'll open an issue an close this one
