### ISSUE TITLE
Incompatible with Quilt

### ISSUE THREAD

**Issue by Sunconure11** [PssbleTrngle/SliceAndDice#51]
### What happened?

Tried to load the Fabric build on Quilt. Got an error instead. Of note is that there is a separate set of libraries for Kotlin on Quilt.

### Loader

fabric

### Mod Version

2.1.0

### Minecraft Version

1.19

### Relevant log output

```shell
https://gist.github.com/Sunconure11/f7c8feb00c1955691688397334705080
```

**Comment by PssbleTrngle** [comment]
Have you tried what happens if you add [qkl](https://modrinth.com/mod/qkl)?

**Comment by Sunconure11** [comment]
I have that already…

**Comment by ZekeZDev** [comment]
@PssbleTrngle it seems like the issue is related to the 1.19.2 version of slice and dice requiring a newer version of kotlin libraries than provided by qkl. I was actually able to run the mod by removing qkl as it would use the dependency of fabric-language-kotlin from another mod. you can actually see this in the above gist:

```
Dependency for {org.quiltmc.loader.impl.plugin.fabric.FabricModOption 'sliceanddice' from <mods>/sliceanddice-fabric-2.1.0.jar} on fabric-language-kotlin versions [>1.9.1+kotlin.1.8.10] (1 valid options, 1 invalid options)
	+ {org.quiltmc.loader.impl.plugin.fabric.FabricModOption 'fabric-language-kotlin' from <mods>/direbats-3.1.0+1.19.2.jar!/META-INF/jars/fabric-language-kotlin-1.9.3+kotlin.1.8.20.jar} {org.quiltmc.loader.impl.plugin.fabric.FabricModOption 'fabric-language-kotlin' from <mods>/direbats-3.1.0+1.19.2.jar!/META-INF/jars/fabric-language-kotlin-1.9.3+kotlin.1.8.20.jar}
	x provided mod 'fabric-language-kotlin' from {org.quiltmc.loader.impl.plugin.quilt.QuiltModOption 'qkl_core' from <mods>/quilt-kotlin-libraries-1.0.2+kt.1.8.0+flk.1.9.0.jar!/META-INF/jars/quilt-kotlin-libraries-core-1.0.2+kt.1.8.0+flk.1.9.0.jar} {org.quiltmc.loader.impl.plugin.quilt.QuiltModOption 'qkl_core' from <mods>/quilt-kotlin-libraries-1.0.2+kt.1.8.0+flk.1.9.0.jar!/META-INF/jars/quilt-kotlin-libraries-core-1.0.2+kt.1.8.0+flk.1.9.0.jar}
```

This specifies that DireBats actually has a useable version and is causing a conflict. removing qkl its likely that the modpack will launch however removing direbats will result in a different error such as:
![image](https://github.com/PssbleTrngle/SliceAndDice/assets/81902668/085aacc1-85fb-40b9-bacf-bf0c9185c262)
Terminal:
```
-- Error 1 --
Create Slice & Dice requires version [1.9.1+kotlin.1.8.10, ∞) of fabric-language-kotlin, which is missing!
Create Slice & Dice is loaded from /home/*/.var/app/org.prismlauncher.PrismLauncher/data/PrismLauncher/instances/[modpack]/.minecraft/mods/sliceanddice-fabric-2.1.2-fabric.jar

```

**Comment by PssbleTrngle** [comment]
Sounds like qkl would need to update their kotlin libraries for this mod to work on quilt

**Comment by SplendidAlakey** [comment]
They already have, but the way QKL is set up, they don't have the manpower to maintain both QKL and FLK for all versions, so they chose to update FLK separately as a standalone core file: https://www.curseforge.com/minecraft/mc-mods/qkl/download/4490417. Note: CF App is incapable of downloading additional files like that, so it's not suitable for modpacks, ask CF to add that feature.

Alternatively, you can just use FLK itself, it's fully compatible with Quilt, and, unless you are using QKL specific mods, there's no reason to prefer QKL for the time being.

**Comment by emifloofy** [comment]
i feel like there's an important question to ask, though. does the mod use any features from the two versions of FLK that haven't been ported over to QKL? the only thing that i can see the FLK updates being about is just bumping up the versions of the bundled libraries, so a part of me is a little skeptical about whether it's actually all that important for slice and dice to require the newest version of FKL, when it could possibly just require a lower version, such as 1.9.4 which is currently the newest version of FLK that QKL supports.

i don't know though, i barely know anything when it comes to minecraft modding. i am simply curious whether slice and dice outright *requires* those new versions of FKL...

**Comment by PssbleTrngle** [comment]
no it's definitly not important, I very likely do not need the newest version of fabric-language-kotlin.
If I understand correctly, it's because I am requiring a newer version than `1.9.1+kotlin.1.8.10` [here](https://github.com/PssbleTrngle/SliceAndDice-Fabric/blob/631f7fbddd223e5f9804d22a1cc1cc4abcae834e/src/main/resources/fabric.mod.json#L38).
But shouldn't that be low enought for gqk than, if they support up to `1.9.4`?

**Comment by PssbleTrngle** [comment]
I could also just replace it with a wildcard `*`, because most people would probably use the latest version of either of the libraries anyway and it's only important that they have installed them at all

**Comment by emifloofy** [comment]
turns out that i didn't read properly, the latest QKL version for 1.19.2 is actually 1.9.0, and for some reason it seems like they don't backport QKL although there is some more stuff that i found that i don't understand at all.

**Comment by PssbleTrngle** [comment]
Then I will set the minimum version requirement to 1.9.0 and release a new version with that.
If something still not works, feel free to reopen this
